disabled_rules: # rule identifiers to exclude from running
  - closing_brace
  - colon
  - comma
  - conditional_binding_cascade
  - control_statement
  - custom_rules
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - empty_count
  - empty_parentheses_with_trailing_closure
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - for_where
  - function_body_length
  - function_parameter_count
  - leading_whitespace
  - legacy_constant
  - legacy_constructor
  - line_length
  - mark
  - missing_docs
  - multiple_closures_with_trailing_closure
  - nesting
  # - opening_brace
  - operator_whitespace
  - return_arrow_whitespace
  - redundant_discardable_let
  - redundant_optional_initialization
  - redundant_void_return
  - statement_position
  - shorthand_operator
  - todo
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - valid_docs
  - variable_name
  - void_return
  - unused_closure_parameter
  - unneeded_break_in_switch
  - unused_optional_binding
  - private_over_fileprivate
  - weak_delegate
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
